FROM banacorn/agda:latest

RUN mkdir code

WORKDIR /usr/share 

RUN  wget -O agda-stdlib.tar https://github.com/agda/agda-stdlib/archive/v1.2.tar.gz
RUN tar -zxvf agda-stdlib.tar


WORKDIR /root
RUN mkdir .agda
RUN echo "/usr/share/agda-stdlib-1.2/standard-library.agda-lib" >> /root/.agda/libraries
RUN echo "standard-library" >> /root/.agda/defaults
RUN cabal update
RUN cabal install ieee754

WORKDIR /code

ENTRYPOINT ["/bin/bash", "-c", "tail -f /dev/null"]