name: Coq Docker Practice

on: [push]

jobs:
  coq_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: run docker image and compile coq file
        run: |
          docker run -d --name coq-container -v "./coq-code:/home/coq/code" coqorg/coq:latest
          docker exec coq-container /bin/bash -c "coqc ./code/Basics.v"
          docker stop coq-container
          docker rm coq-container